{% set python_min = python_min|default("3.8") %}
{% set name = "streamlit-flow-component" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamlit-flow-component-{{ version }}.tar.gz
  sha256: 16998d94731f494358d3ce03a73795e127c39fcefa0662666f524bd017493388

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - streamlit >=1.0.0

test:
  imports:
    - streamlit_flow
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - streamlit >=1.0.0

about:
  home: https://github.com/dkapur17/streamlit-flow
  summary: Streamlit Component Wrapper for React Flow
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
    - ywang-aq
