{% set name = "streamlit-flow-component" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 16998d94731f494358d3ce03a73795e127c39fcefa0662666f524bd017493388

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - streamlit >=1.0.0

test:
  files:
    - tests
  imports:
    - streamlit_flow
    - streamlit_flow.elements
    - streamlit_flow.state
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # llm testing
    - pytest -v tests/llm_tests.py
  requires:
    - pip
    - pytest

about:
  home: https://stflow.streamlit.app
  summary: Streamlit Flow is a library for creating and visualizing flow diagrams in Streamlit.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Streamlit Flow is a library for creating and visualizing flow diagrams in Streamlit.
    Powered by ReactFlow, Streamlit Flow provides an extensive wrapper over ReactFlow while also adding
    several quality of life features like Context Menus and a Layout Engine, all accessible through the simplicity of Streamlit.
  doc_url: https://stflow.streamlit.app
  dev_url: https://github.com/dkapur17/streamlit-flow

extra:
  recipe-maintainers:
    - apmorton
    - ywang-aq
